---
- hosts: webservers
  sudo: yes
  vars:
    httpd_port: 80
    doc_dir: /ansible/
    doc_root: /var/www/
    max_clients: 5
  vars_prompt:
  - name: username
    prompt: What is your name? What is  your Quest? What is your fav color?
 
  tasks:
  - name: Ensure that Apache is installed
    apt: name=apache2 state=present
    when: ansible_os_family == "Debian"

  - name: Start Apache Services
    service: name=apache2 enabled=yes state=started
    when: ansible_os_family == "Debian"

  - name: Deploy  Configuration File
    template: src=templates/httpd.j2 dest=/etc/apache2/httpd.conf
    notify:
      - Restart Apache
  - name: Copy Site File
    template: src=templates/index.j2 dest={{ doc_root }}/ansible.html

  handlers:
  - name: Restart Apache
    service: name=httpd state=restared

- hosts: dbservers
  sudo: yes

  tasks:
  - name: Ensure MySQL is installed
    apt: name=mysql-server state=present
    when: ansible_os_family == "Debian"

  - name: start MySQL
    service: name=mysqld state=started

- hosts: webservers:dbservers
  sudo : yes

  tasks:
  - name: Stop IPTABLES NOW!!!
    service: name=iptables state=stopped
    when: ansible_os_family == "RedHat"

